### PR TITLE
Allow developers to use a custom font as well as FontAwesome font.

### PR DESCRIPTION
**Pull request by deivers**
Dave Grady, I don't know if you are open to pull requests on this, but I found your library today and would like to use it intact as a cocoapod.  I need the flexibility to specify my own custom font when an image that I need isn't in FontAwesome.  I didn't see how I could enable this by subclassing.  Maybe a few other developers would like the option as well.
-Doug Ivers

### CODE REVIEW

**Comment by sweetmandm** [comment]
Hi Doug,

Dave Sweetman here actually, Dave Gandy is the author of FontAwesome, I just wrapped it up for use in iOS. 

I guess this would be doable, it would just require refactoring the meat of of +imageWithIcon:iconColor:iconSize:imageSize: into a method called something like +imageWithText:font:iconColor:iconSize:imageSize:. If you add this functionality, please also put an example in the Readme to explain its utility.

I actually ran into this same problem a little while ago, but decided to just duplicate the project with a different icon font, sine the other icon font I wanted to use was also under a non-attribution open source license. The other project is using ionicons - https://github.com/TapTemplate/ionicons-iOS. It had some changes that I just merged back into this project, such as modifying an existing UILabel with the icon font, but if you plan to add the above functionality I’ll wait for that before doing another cocoapods release.

Thanks,
- Dave

P.S. I found your Linkedin profile (assuming you’re the Doug Ivers @ Role Model Software) and I’m making the move to Raliegh from Los Angeles this summer, pretty excited about it!

**Comment by deivers** [comment]
Well at least I got the first name right!  :-)
Yes, that's me on LinkedIn.  We've got a good iOS developer community here in central NC:  http://www.meetup.com/nscoderrtp/

So the first argument of +imageWithText:font:iconColor:iconSize:imageSize:
would be a char code such as @"\uf190", right?

**Comment by sweetmandm** [comment]
Yeah, in the case of an icon font the first parameter would be something like that

**Comment by deivers** [comment]
Ok, let me know what you think of the updated method name.  Any other suggestions?

**Comment by sweetmandm** [comment]
Oh sorry I didn't realize you'd already implemented it, since I was interacting through email and somehow totally missed the pull request. Sorry the naming thing is pretty trivial, I would have merged earlier if I'd realized it already was good to go.

**Comment by sweetmandm** [comment]
Sorry I must be really out of it (traveling currently) and majorly screwed up the merge when I push -f'd at the wrong moment, did some rebasing, basically a good ol git time, so I had to go back in the reflog to get an original command-line merge I did and abandon my second attempt where I merged with github's nice ui. Anyway, the project history doesn't look as good as it could or reflect the correct contributor count, but the changes are in.

The only substantial change I made to your code was to pass a UIFont instance to the -imageWithText: font:... method instead of a font name string, and then get the icon size from the font's pointSize.

I'm going through the cocoapods stuff now so hopefully the 1.2 pod will be up in the next hour or so.

**Comment by deivers** [comment]
Excellent!  I'll be able to keep this as a cocoapod in my codebase instead of locally modified source files in order to access a custom font.  Thanks!

**Pull request merged**
